// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackCommand = `-- name: AckCommand :exec
UPDATE commands
SET status = $2, acked_at = NOW(), result = $3
WHERE id = $1
`

type AckCommandParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
	Result []byte      `json:"result"`
}

func (q *Queries) AckCommand(ctx context.Context, arg AckCommandParams) error {
	_, err := q.db.Exec(ctx, ackCommand, arg.ID, arg.Status, arg.Result)
	return err
}

const createCommand = `-- name: CreateCommand :one
INSERT INTO commands (id, node_id, sandbox_id, command_type, payload, timeout_seconds)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, node_id, sandbox_id, command_type, payload, status, dispatched_at, acked_at, result, timeout_seconds, created_at
`

type CreateCommandParams struct {
	ID             pgtype.UUID `json:"id"`
	NodeID         pgtype.UUID `json:"node_id"`
	SandboxID      pgtype.UUID `json:"sandbox_id"`
	CommandType    string      `json:"command_type"`
	Payload        []byte      `json:"payload"`
	TimeoutSeconds int32       `json:"timeout_seconds"`
}

func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error) {
	row := q.db.QueryRow(ctx, createCommand,
		arg.ID,
		arg.NodeID,
		arg.SandboxID,
		arg.CommandType,
		arg.Payload,
		arg.TimeoutSeconds,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SandboxID,
		&i.CommandType,
		&i.Payload,
		&i.Status,
		&i.DispatchedAt,
		&i.AckedAt,
		&i.Result,
		&i.TimeoutSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommandsForSandbox = `-- name: DeleteCommandsForSandbox :exec
DELETE FROM commands WHERE sandbox_id = $1
`

// Phase 33-Real-8 — purge command rows referencing a sandbox before
// DELETE FROM sandboxes can succeed (the commands_sandbox_id_fkey FK
// has no ON DELETE CASCADE). Used by the post-stop-ack pool cleanup
// path that destroys terminal pool sandboxes inline rather than waiting
// on cron.
func (q *Queries) DeleteCommandsForSandbox(ctx context.Context, sandboxID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommandsForSandbox, sandboxID)
	return err
}

const getCommand = `-- name: GetCommand :one
SELECT id, node_id, sandbox_id, command_type, payload, status, dispatched_at, acked_at, result, timeout_seconds, created_at FROM commands WHERE id = $1
`

func (q *Queries) GetCommand(ctx context.Context, id pgtype.UUID) (Command, error) {
	row := q.db.QueryRow(ctx, getCommand, id)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SandboxID,
		&i.CommandType,
		&i.Payload,
		&i.Status,
		&i.DispatchedAt,
		&i.AckedAt,
		&i.Result,
		&i.TimeoutSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const pollPendingCommands = `-- name: PollPendingCommands :many
UPDATE commands
SET status = 'dispatched', dispatched_at = NOW()
WHERE id IN (
    SELECT c.id FROM commands c
    WHERE c.node_id = $1 AND c.status = 'pending'
    ORDER BY c.created_at ASC
    LIMIT 10
    FOR UPDATE SKIP LOCKED
)
RETURNING id, node_id, sandbox_id, command_type, payload, status, dispatched_at, acked_at, result, timeout_seconds, created_at
`

func (q *Queries) PollPendingCommands(ctx context.Context, nodeID pgtype.UUID) ([]Command, error) {
	rows, err := q.db.Query(ctx, pollPendingCommands, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.SandboxID,
			&i.CommandType,
			&i.Payload,
			&i.Status,
			&i.DispatchedAt,
			&i.AckedAt,
			&i.Result,
			&i.TimeoutSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
