// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEventsBySandbox = `-- name: ListEventsBySandbox :many
SELECT id, sandbox_id, node_id, event_type, actor, prev_state, next_state, payload, created_at FROM events WHERE sandbox_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListEventsBySandboxParams struct {
	SandboxID pgtype.UUID `json:"sandbox_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListEventsBySandbox(ctx context.Context, arg ListEventsBySandboxParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsBySandbox, arg.SandboxID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.NodeID,
			&i.EventType,
			&i.Actor,
			&i.PrevState,
			&i.NextState,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByType = `-- name: ListEventsByType :many
SELECT id, sandbox_id, node_id, event_type, actor, prev_state, next_state, payload, created_at FROM events WHERE event_type = $1 ORDER BY created_at DESC LIMIT $2
`

type ListEventsByTypeParams struct {
	EventType string `json:"event_type"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListEventsByType(ctx context.Context, arg ListEventsByTypeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByType, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.NodeID,
			&i.EventType,
			&i.Actor,
			&i.PrevState,
			&i.NextState,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEvents = `-- name: ListRecentEvents :many
SELECT id, sandbox_id, node_id, event_type, actor, prev_state, next_state, payload, created_at FROM events ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRecentEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SandboxID,
			&i.NodeID,
			&i.EventType,
			&i.Actor,
			&i.PrevState,
			&i.NextState,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEvent = `-- name: RecordEvent :one
INSERT INTO events (sandbox_id, node_id, event_type, actor, prev_state, next_state, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, sandbox_id, node_id, event_type, actor, prev_state, next_state, payload, created_at
`

type RecordEventParams struct {
	SandboxID pgtype.UUID `json:"sandbox_id"`
	NodeID    pgtype.UUID `json:"node_id"`
	EventType string      `json:"event_type"`
	Actor     string      `json:"actor"`
	PrevState pgtype.Text `json:"prev_state"`
	NextState pgtype.Text `json:"next_state"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, recordEvent,
		arg.SandboxID,
		arg.NodeID,
		arg.EventType,
		arg.Actor,
		arg.PrevState,
		arg.NextState,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SandboxID,
		&i.NodeID,
		&i.EventType,
		&i.Actor,
		&i.PrevState,
		&i.NextState,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
