// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Command struct {
	ID             pgtype.UUID        `json:"id"`
	NodeID         pgtype.UUID        `json:"node_id"`
	SandboxID      pgtype.UUID        `json:"sandbox_id"`
	CommandType    string             `json:"command_type"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	DispatchedAt   pgtype.Timestamptz `json:"dispatched_at"`
	AckedAt        pgtype.Timestamptz `json:"acked_at"`
	Result         []byte             `json:"result"`
	TimeoutSeconds int32              `json:"timeout_seconds"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID        int64              `json:"id"`
	SandboxID pgtype.UUID        `json:"sandbox_id"`
	NodeID    pgtype.UUID        `json:"node_id"`
	EventType string             `json:"event_type"`
	Actor     string             `json:"actor"`
	PrevState pgtype.Text        `json:"prev_state"`
	NextState pgtype.Text        `json:"next_state"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Node struct {
	ID                pgtype.UUID        `json:"id"`
	Hostname          string             `json:"hostname"`
	TailscaleIp       netip.Addr         `json:"tailscale_ip"`
	AgentListenPort   int32              `json:"agent_listen_port"`
	CapacityMb        int32              `json:"capacity_mb"`
	CapacityCpu       pgtype.Numeric     `json:"capacity_cpu"`
	UsedMb            int32              `json:"used_mb"`
	RunningContainers int32              `json:"running_containers"`
	Status            string             `json:"status"`
	AgentVersion      string             `json:"agent_version"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	RegisteredAt      pgtype.Timestamptz `json:"registered_at"`
	Metadata          []byte             `json:"metadata"`
	AgentToken        string             `json:"agent_token"`
}

type Sandbox struct {
	ID                 pgtype.UUID        `json:"id"`
	AppName            string             `json:"app_name"`
	UserID             string             `json:"user_id"`
	NodeID             pgtype.UUID        `json:"node_id"`
	ContainerID        pgtype.Text        `json:"container_id"`
	HostPort           pgtype.Int4        `json:"host_port"`
	Image              string             `json:"image"`
	State              string             `json:"state"`
	StateVersion       int32              `json:"state_version"`
	Resources          []byte             `json:"resources"`
	Env                []byte             `json:"env"`
	IdleTimeoutSeconds int32              `json:"idle_timeout_seconds"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	LastActiveAt       pgtype.Timestamptz `json:"last_active_at"`
	FailureCount       int32              `json:"failure_count"`
	Metadata           []byte             `json:"metadata"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
}
