// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSandboxesByNode = `-- name: CountActiveSandboxesByNode :one
SELECT count(*)::int FROM sandboxes WHERE node_id = $1 AND state NOT IN ('destroyed', 'stopped')
`

func (q *Queries) CountActiveSandboxesByNode(ctx context.Context, nodeID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveSandboxesByNode, nodeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, hostname, tailscale_ip, agent_listen_port, capacity_mb, capacity_cpu, agent_version, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, hostname, tailscale_ip, agent_listen_port, capacity_mb, capacity_cpu, used_mb, running_containers, status, agent_version, last_seen_at, registered_at, metadata, agent_token
`

type CreateNodeParams struct {
	ID              pgtype.UUID    `json:"id"`
	Hostname        string         `json:"hostname"`
	TailscaleIp     netip.Addr     `json:"tailscale_ip"`
	AgentListenPort int32          `json:"agent_listen_port"`
	CapacityMb      int32          `json:"capacity_mb"`
	CapacityCpu     pgtype.Numeric `json:"capacity_cpu"`
	AgentVersion    string         `json:"agent_version"`
	Metadata        []byte         `json:"metadata"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.Hostname,
		arg.TailscaleIp,
		arg.AgentListenPort,
		arg.CapacityMb,
		arg.CapacityCpu,
		arg.AgentVersion,
		arg.Metadata,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.TailscaleIp,
		&i.AgentListenPort,
		&i.CapacityMb,
		&i.CapacityCpu,
		&i.UsedMb,
		&i.RunningContainers,
		&i.Status,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.RegisteredAt,
		&i.Metadata,
		&i.AgentToken,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, hostname, tailscale_ip, agent_listen_port, capacity_mb, capacity_cpu, used_mb, running_containers, status, agent_version, last_seen_at, registered_at, metadata, agent_token FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id pgtype.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.TailscaleIp,
		&i.AgentListenPort,
		&i.CapacityMb,
		&i.CapacityCpu,
		&i.UsedMb,
		&i.RunningContainers,
		&i.Status,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.RegisteredAt,
		&i.Metadata,
		&i.AgentToken,
	)
	return i, err
}

const getNodeByHostnameAndIP = `-- name: GetNodeByHostnameAndIP :one
SELECT id, hostname, tailscale_ip, agent_listen_port, capacity_mb, capacity_cpu, used_mb, running_containers, status, agent_version, last_seen_at, registered_at, metadata, agent_token FROM nodes WHERE hostname = $1 AND tailscale_ip = $2
`

type GetNodeByHostnameAndIPParams struct {
	Hostname    string     `json:"hostname"`
	TailscaleIp netip.Addr `json:"tailscale_ip"`
}

func (q *Queries) GetNodeByHostnameAndIP(ctx context.Context, arg GetNodeByHostnameAndIPParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByHostnameAndIP, arg.Hostname, arg.TailscaleIp)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.TailscaleIp,
		&i.AgentListenPort,
		&i.CapacityMb,
		&i.CapacityCpu,
		&i.UsedMb,
		&i.RunningContainers,
		&i.Status,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.RegisteredAt,
		&i.Metadata,
		&i.AgentToken,
	)
	return i, err
}

const listHealthyNodes = `-- name: ListHealthyNodes :many
SELECT id, hostname, tailscale_ip, agent_listen_port, capacity_mb, capacity_cpu, used_mb, running_containers, status, agent_version, last_seen_at, registered_at, metadata, agent_token FROM nodes WHERE status IN ('healthy') ORDER BY (capacity_mb - used_mb) DESC
`

func (q *Queries) ListHealthyNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listHealthyNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.TailscaleIp,
			&i.AgentListenPort,
			&i.CapacityMb,
			&i.CapacityCpu,
			&i.UsedMb,
			&i.RunningContainers,
			&i.Status,
			&i.AgentVersion,
			&i.LastSeenAt,
			&i.RegisteredAt,
			&i.Metadata,
			&i.AgentToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, hostname, tailscale_ip, agent_listen_port, capacity_mb, capacity_cpu, used_mb, running_containers, status, agent_version, last_seen_at, registered_at, metadata, agent_token FROM nodes ORDER BY registered_at DESC
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.TailscaleIp,
			&i.AgentListenPort,
			&i.CapacityMb,
			&i.CapacityCpu,
			&i.UsedMb,
			&i.RunningContainers,
			&i.Status,
			&i.AgentVersion,
			&i.LastSeenAt,
			&i.RegisteredAt,
			&i.Metadata,
			&i.AgentToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeHeartbeat = `-- name: UpdateNodeHeartbeat :exec
UPDATE nodes SET used_mb = $2, running_containers = $3, status = 'healthy', last_seen_at = NOW() WHERE id = $1
`

type UpdateNodeHeartbeatParams struct {
	ID                pgtype.UUID `json:"id"`
	UsedMb            int32       `json:"used_mb"`
	RunningContainers int32       `json:"running_containers"`
}

func (q *Queries) UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) error {
	_, err := q.db.Exec(ctx, updateNodeHeartbeat, arg.ID, arg.UsedMb, arg.RunningContainers)
	return err
}

const updateNodeStatus = `-- name: UpdateNodeStatus :exec
UPDATE nodes SET status = $2 WHERE id = $1
`

type UpdateNodeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error {
	_, err := q.db.Exec(ctx, updateNodeStatus, arg.ID, arg.Status)
	return err
}

const updateNodeToken = `-- name: UpdateNodeToken :exec
UPDATE nodes SET agent_token = $1, agent_version = $2, last_seen_at = NOW() WHERE id = $3
`

type UpdateNodeTokenParams struct {
	AgentToken   string      `json:"agent_token"`
	AgentVersion string      `json:"agent_version"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateNodeToken(ctx context.Context, arg UpdateNodeTokenParams) error {
	_, err := q.db.Exec(ctx, updateNodeToken, arg.AgentToken, arg.AgentVersion, arg.ID)
	return err
}
