// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandboxes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignSandboxToNode = `-- name: AssignSandboxToNode :one
UPDATE sandboxes
SET node_id = $1, host_port = $2, container_id = $3, state = 'starting', updated_at = NOW(), state_version = state_version + 1
WHERE id = $4 AND state = 'pending'
RETURNING id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at
`

type AssignSandboxToNodeParams struct {
	NodeID      pgtype.UUID `json:"node_id"`
	HostPort    pgtype.Int4 `json:"host_port"`
	ContainerID pgtype.Text `json:"container_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) AssignSandboxToNode(ctx context.Context, arg AssignSandboxToNodeParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, assignSandboxToNode,
		arg.NodeID,
		arg.HostPort,
		arg.ContainerID,
		arg.ID,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
		&i.VerifiedAt,
	)
	return i, err
}

const assignSandboxToNodeUnderCap = `-- name: AssignSandboxToNodeUnderCap :one
UPDATE sandboxes AS s
SET node_id = $1, state = 'starting', updated_at = NOW(), state_version = state_version + 1
WHERE s.id = $2 AND s.state = 'pending'
  AND (
    SELECT count(*) FROM sandboxes s2
    WHERE s2.node_id = $1
      AND s2.state IN ('pending', 'starting', 'running', 'restarting', 'destroying')
  ) < $3::int
RETURNING s.id, s.app_name, s.user_id, s.node_id, s.container_id, s.host_port, s.image, s.state, s.state_version, s.resources, s.env, s.idle_timeout_seconds, s.created_at, s.updated_at, s.last_active_at, s.failure_count, s.metadata, s.verified_at
`

type AssignSandboxToNodeUnderCapParams struct {
	NodeID pgtype.UUID `json:"node_id"`
	ID     pgtype.UUID `json:"id"`
	Cap    int32       `json:"cap"`
}

// Atomic conditional assign for the per-node count cap. Assigns the pending
// sandbox to the node ONLY IF the node's live schedulable count is strictly
// below @cap (an INTEGER, the per-node ceiling), measured in the SAME
// statement's snapshot. The caller MUST hold a per-node advisory lock
// (pg_advisory_xact_lock) in the enclosing transaction BEFORE running this so
// concurrent assigns to the same node serialize — without that, two
// simultaneous creates would each read the same pre-burst count and both pass
// (the TOCTOU window this guards against). When the node is at/over cap the
// UPDATE matches zero rows and returns no row (pgx.ErrNoRows), so the caller
// picks another node or returns ErrNoCapacity.
//
// NOTE: @cap is a named parameter (sqlc.arg) so the generated binding is a
// typed INT field (Cap int32), NOT a UUID. A previous attempt left this as a
// bare $3 positional which sqlc mis-bound to the node UUID, producing
// "operator does not exist: bigint < uuid" at runtime on every capped assign.
func (q *Queries) AssignSandboxToNodeUnderCap(ctx context.Context, arg AssignSandboxToNodeUnderCapParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, assignSandboxToNodeUnderCap, arg.NodeID, arg.ID, arg.Cap)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
		&i.VerifiedAt,
	)
	return i, err
}

const countSandboxesByState = `-- name: CountSandboxesByState :many
SELECT state, COUNT(*)::int AS count
FROM sandboxes
GROUP BY state
`

type CountSandboxesByStateRow struct {
	State string `json:"state"`
	Count int32  `json:"count"`
}

func (q *Queries) CountSandboxesByState(ctx context.Context) ([]CountSandboxesByStateRow, error) {
	rows, err := q.db.Query(ctx, countSandboxesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSandboxesByStateRow{}
	for rows.Next() {
		var i CountSandboxesByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandboxes (id, app_name, user_id, image, state, resources, env, idle_timeout_seconds, metadata)
VALUES ($1, $2, $3, $4, 'pending', $5, $6, $7, $8)
RETURNING id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at
`

type CreateSandboxParams struct {
	ID                 pgtype.UUID `json:"id"`
	AppName            string      `json:"app_name"`
	UserID             string      `json:"user_id"`
	Image              string      `json:"image"`
	Resources          []byte      `json:"resources"`
	Env                []byte      `json:"env"`
	IdleTimeoutSeconds int32       `json:"idle_timeout_seconds"`
	Metadata           []byte      `json:"metadata"`
}

func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, createSandbox,
		arg.ID,
		arg.AppName,
		arg.UserID,
		arg.Image,
		arg.Resources,
		arg.Env,
		arg.IdleTimeoutSeconds,
		arg.Metadata,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
		&i.VerifiedAt,
	)
	return i, err
}

const deleteSandbox = `-- name: DeleteSandbox :exec
DELETE FROM sandboxes WHERE id = $1
`

func (q *Queries) DeleteSandbox(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSandbox, id)
	return err
}

const getSandbox = `-- name: GetSandbox :one
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at FROM sandboxes WHERE id = $1
`

func (q *Queries) GetSandbox(ctx context.Context, id pgtype.UUID) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandbox, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
		&i.VerifiedAt,
	)
	return i, err
}

const getSandboxByAppName = `-- name: GetSandboxByAppName :one
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at FROM sandboxes WHERE app_name = $1
`

func (q *Queries) GetSandboxByAppName(ctx context.Context, appName string) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxByAppName, appName)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
		&i.VerifiedAt,
	)
	return i, err
}

const incrementSandboxFailureCount = `-- name: IncrementSandboxFailureCount :one
UPDATE sandboxes
SET failure_count = failure_count + 1, updated_at = NOW()
WHERE id = $1
RETURNING id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at
`

func (q *Queries) IncrementSandboxFailureCount(ctx context.Context, id pgtype.UUID) (Sandbox, error) {
	row := q.db.QueryRow(ctx, incrementSandboxFailureCount, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
		&i.VerifiedAt,
	)
	return i, err
}

const listIdleSandboxes = `-- name: ListIdleSandboxes :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at FROM sandboxes
WHERE state = 'running'
  AND last_active_at < NOW() - (idle_timeout_seconds || ' seconds')::INTERVAL
ORDER BY last_active_at ASC
`

func (q *Queries) ListIdleSandboxes(ctx context.Context) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listIdleSandboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningSandboxesByNode = `-- name: ListRunningSandboxesByNode :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at FROM sandboxes WHERE node_id = $1 AND state = 'running' ORDER BY created_at ASC
`

func (q *Queries) ListRunningSandboxesByNode(ctx context.Context, nodeID pgtype.UUID) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listRunningSandboxesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxes = `-- name: ListSandboxes :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at FROM sandboxes ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListSandboxes(ctx context.Context, limit int32) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesByNode = `-- name: ListSandboxesByNode :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at FROM sandboxes WHERE node_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByNode(ctx context.Context, nodeID pgtype.UUID) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesByState = `-- name: ListSandboxesByState :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at FROM sandboxes WHERE state = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByState(ctx context.Context, state string) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesByUser = `-- name: ListSandboxesByUser :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at FROM sandboxes WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByUser(ctx context.Context, userID string) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesForNode = `-- name: ListSandboxesForNode :many
SELECT app_name, state, created_at
FROM sandboxes
WHERE node_id = $1
  AND state IN ('pending','starting','running','restarting')
`

type ListSandboxesForNodeRow struct {
	AppName   string             `json:"app_name"`
	State     string             `json:"state"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSandboxesForNode(ctx context.Context, nodeID pgtype.UUID) ([]ListSandboxesForNodeRow, error) {
	rows, err := q.db.Query(ctx, listSandboxesForNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSandboxesForNodeRow{}
	for rows.Next() {
		var i ListSandboxesForNodeRow
		if err := rows.Scan(&i.AppName, &i.State, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoppedExpired = `-- name: ListStoppedExpired :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at FROM sandboxes
WHERE state = 'stopped'
  AND updated_at < NOW() - ($1::int || ' seconds')::INTERVAL
ORDER BY updated_at ASC
`

// Sleep-not-destroy (2026-06-11): slept (docker-stopped, kept-on-disk)
// sandboxes older than the retention window — the second-tier reaper
// destroys these for real. updated_at is bumped by the running->stopped
// transition, so this measures time-since-sleep.
func (q *Queries) ListStoppedExpired(ctx context.Context, retentionSeconds int32) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listStoppedExpired, retentionSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerminalSandboxesForNode = `-- name: ListTerminalSandboxesForNode :many
SELECT id, app_name, container_id
FROM sandboxes
WHERE node_id = $1
  AND state IN ('failed', 'destroying', 'destroyed')
  AND container_id IS NOT NULL
  AND container_id <> ''
`

type ListTerminalSandboxesForNodeRow struct {
	ID          pgtype.UUID `json:"id"`
	AppName     string      `json:"app_name"`
	ContainerID pgtype.Text `json:"container_id"`
}

// Phase 33-Real-7 — returns rows the reconciler must issue stop_sandbox
// for: state is terminal but the agent still observes the container,
// so the orphan needs explicit destroy dispatch.
func (q *Queries) ListTerminalSandboxesForNode(ctx context.Context, nodeID pgtype.UUID) ([]ListTerminalSandboxesForNodeRow, error) {
	rows, err := q.db.Query(ctx, listTerminalSandboxesForNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTerminalSandboxesForNodeRow{}
	for rows.Next() {
		var i ListTerminalSandboxesForNodeRow
		if err := rows.Scan(&i.ID, &i.AppName, &i.ContainerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSandboxAgentLost = `-- name: MarkSandboxAgentLost :exec
UPDATE sandboxes
SET state = 'destroyed',
    metadata = metadata || jsonb_build_object('reason', 'agent_lost_at_heartbeat'),
    verified_at = NOW()
WHERE app_name = $1
  AND node_id = $2
  AND state IN ('pending','starting','running','restarting')
  AND created_at < NOW() - INTERVAL '60 seconds'
`

type MarkSandboxAgentLostParams struct {
	AppName string      `json:"app_name"`
	NodeID  pgtype.UUID `json:"node_id"`
}

func (q *Queries) MarkSandboxAgentLost(ctx context.Context, arg MarkSandboxAgentLostParams) error {
	_, err := q.db.Exec(ctx, markSandboxAgentLost, arg.AppName, arg.NodeID)
	return err
}

const markSandboxDestroyed = `-- name: MarkSandboxDestroyed :exec
UPDATE sandboxes
SET state = 'destroyed',
    metadata = metadata || jsonb_build_object('reason', $2::text),
    verified_at = NOW(),
    updated_at = NOW(),
    state_version = state_version + 1
WHERE app_name = $1
  AND state IN ('pending','starting','running','restarting')
`

type MarkSandboxDestroyedParams struct {
	AppName string `json:"app_name"`
	Reason  string `json:"reason"`
}

func (q *Queries) MarkSandboxDestroyed(ctx context.Context, arg MarkSandboxDestroyedParams) error {
	_, err := q.db.Exec(ctx, markSandboxDestroyed, arg.AppName, arg.Reason)
	return err
}

const markSandboxVerified = `-- name: MarkSandboxVerified :exec
UPDATE sandboxes
SET verified_at = NOW(), state = $2
WHERE app_name = $1
  AND verified_at < NOW()
  AND state IN ('pending','starting','running','restarting','stopped')
`

type MarkSandboxVerifiedParams struct {
	AppName string `json:"app_name"`
	State   string `json:"state"`
}

// Phase 33-Real-7 — guard against silent terminal-state flip. Without
// the state-IN clause, a heartbeat reporting state='running' for an
// app_name whose row is failed/destroying/destroyed would silently
// resurrect it. Terminal rows must only leave terminal state via the
// lifecycle layer's explicit transitions.
func (q *Queries) MarkSandboxVerified(ctx context.Context, arg MarkSandboxVerifiedParams) error {
	_, err := q.db.Exec(ctx, markSandboxVerified, arg.AppName, arg.State)
	return err
}

const resetSandboxFailureCount = `-- name: ResetSandboxFailureCount :exec
UPDATE sandboxes
SET failure_count = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetSandboxFailureCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetSandboxFailureCount, id)
	return err
}

const transitionSandboxState = `-- name: TransitionSandboxState :one
UPDATE sandboxes
SET state = $1, updated_at = NOW(), state_version = state_version + 1
WHERE id = $2 AND state = $3
RETURNING id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata, verified_at
`

type TransitionSandboxStateParams struct {
	State   string      `json:"state"`
	ID      pgtype.UUID `json:"id"`
	State_2 string      `json:"state_2"`
}

func (q *Queries) TransitionSandboxState(ctx context.Context, arg TransitionSandboxStateParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, transitionSandboxState, arg.State, arg.ID, arg.State_2)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
		&i.VerifiedAt,
	)
	return i, err
}

const updateSandboxLastActive = `-- name: UpdateSandboxLastActive :exec
UPDATE sandboxes SET last_active_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateSandboxLastActive(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSandboxLastActive, id)
	return err
}

const updateSandboxRuntime = `-- name: UpdateSandboxRuntime :exec
UPDATE sandboxes
SET container_id = $1, host_port = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateSandboxRuntimeParams struct {
	ContainerID pgtype.Text `json:"container_id"`
	HostPort    pgtype.Int4 `json:"host_port"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSandboxRuntime(ctx context.Context, arg UpdateSandboxRuntimeParams) error {
	_, err := q.db.Exec(ctx, updateSandboxRuntime, arg.ContainerID, arg.HostPort, arg.ID)
	return err
}
