// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandboxes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignSandboxToNode = `-- name: AssignSandboxToNode :one
UPDATE sandboxes
SET node_id = $1, host_port = $2, container_id = $3, state = 'starting', updated_at = NOW(), state_version = state_version + 1
WHERE id = $4 AND state = 'pending'
RETURNING id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata
`

type AssignSandboxToNodeParams struct {
	NodeID      pgtype.UUID `json:"node_id"`
	HostPort    pgtype.Int4 `json:"host_port"`
	ContainerID pgtype.Text `json:"container_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) AssignSandboxToNode(ctx context.Context, arg AssignSandboxToNodeParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, assignSandboxToNode,
		arg.NodeID,
		arg.HostPort,
		arg.ContainerID,
		arg.ID,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
	)
	return i, err
}

const countSandboxesByState = `-- name: CountSandboxesByState :many
SELECT state, COUNT(*)::int AS count
FROM sandboxes
GROUP BY state
`

type CountSandboxesByStateRow struct {
	State string `json:"state"`
	Count int32  `json:"count"`
}

func (q *Queries) CountSandboxesByState(ctx context.Context) ([]CountSandboxesByStateRow, error) {
	rows, err := q.db.Query(ctx, countSandboxesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSandboxesByStateRow{}
	for rows.Next() {
		var i CountSandboxesByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandboxes (id, app_name, user_id, image, state, resources, env, idle_timeout_seconds, metadata)
VALUES ($1, $2, $3, $4, 'pending', $5, $6, $7, $8)
RETURNING id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata
`

type CreateSandboxParams struct {
	ID                 pgtype.UUID `json:"id"`
	AppName            string      `json:"app_name"`
	UserID             string      `json:"user_id"`
	Image              string      `json:"image"`
	Resources          []byte      `json:"resources"`
	Env                []byte      `json:"env"`
	IdleTimeoutSeconds int32       `json:"idle_timeout_seconds"`
	Metadata           []byte      `json:"metadata"`
}

func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, createSandbox,
		arg.ID,
		arg.AppName,
		arg.UserID,
		arg.Image,
		arg.Resources,
		arg.Env,
		arg.IdleTimeoutSeconds,
		arg.Metadata,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
	)
	return i, err
}

const getSandbox = `-- name: GetSandbox :one
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata FROM sandboxes WHERE id = $1
`

func (q *Queries) GetSandbox(ctx context.Context, id pgtype.UUID) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandbox, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
	)
	return i, err
}

const getSandboxByAppName = `-- name: GetSandboxByAppName :one
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata FROM sandboxes WHERE app_name = $1
`

func (q *Queries) GetSandboxByAppName(ctx context.Context, appName string) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxByAppName, appName)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
	)
	return i, err
}

const incrementSandboxFailureCount = `-- name: IncrementSandboxFailureCount :one
UPDATE sandboxes
SET failure_count = failure_count + 1, updated_at = NOW()
WHERE id = $1
RETURNING id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata
`

func (q *Queries) IncrementSandboxFailureCount(ctx context.Context, id pgtype.UUID) (Sandbox, error) {
	row := q.db.QueryRow(ctx, incrementSandboxFailureCount, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
	)
	return i, err
}

const listIdleSandboxes = `-- name: ListIdleSandboxes :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata FROM sandboxes
WHERE state = 'running'
  AND last_active_at < NOW() - (idle_timeout_seconds || ' seconds')::INTERVAL
ORDER BY last_active_at ASC
`

func (q *Queries) ListIdleSandboxes(ctx context.Context) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listIdleSandboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxes = `-- name: ListSandboxes :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata FROM sandboxes ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListSandboxes(ctx context.Context, limit int32) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesByNode = `-- name: ListSandboxesByNode :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata FROM sandboxes WHERE node_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByNode(ctx context.Context, nodeID pgtype.UUID) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesByState = `-- name: ListSandboxesByState :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata FROM sandboxes WHERE state = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByState(ctx context.Context, state string) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesByUser = `-- name: ListSandboxesByUser :many
SELECT id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata FROM sandboxes WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSandboxesByUser(ctx context.Context, userID string) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.UserID,
			&i.NodeID,
			&i.ContainerID,
			&i.HostPort,
			&i.Image,
			&i.State,
			&i.StateVersion,
			&i.Resources,
			&i.Env,
			&i.IdleTimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.FailureCount,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSandboxFailureCount = `-- name: ResetSandboxFailureCount :exec
UPDATE sandboxes
SET failure_count = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetSandboxFailureCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetSandboxFailureCount, id)
	return err
}

const transitionSandboxState = `-- name: TransitionSandboxState :one
UPDATE sandboxes
SET state = $1, updated_at = NOW(), state_version = state_version + 1
WHERE id = $2 AND state = $3
RETURNING id, app_name, user_id, node_id, container_id, host_port, image, state, state_version, resources, env, idle_timeout_seconds, created_at, updated_at, last_active_at, failure_count, metadata
`

type TransitionSandboxStateParams struct {
	State   string      `json:"state"`
	ID      pgtype.UUID `json:"id"`
	State_2 string      `json:"state_2"`
}

func (q *Queries) TransitionSandboxState(ctx context.Context, arg TransitionSandboxStateParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, transitionSandboxState, arg.State, arg.ID, arg.State_2)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.UserID,
		&i.NodeID,
		&i.ContainerID,
		&i.HostPort,
		&i.Image,
		&i.State,
		&i.StateVersion,
		&i.Resources,
		&i.Env,
		&i.IdleTimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.FailureCount,
		&i.Metadata,
	)
	return i, err
}

const updateSandboxLastActive = `-- name: UpdateSandboxLastActive :exec
UPDATE sandboxes SET last_active_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateSandboxLastActive(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSandboxLastActive, id)
	return err
}
